-- =====================================================================
-- Karthika Stores — database schema (PostgreSQL / Neon)
-- ---------------------------------------------------------------------
-- Money is stored as integer paise to avoid floating point drift.
-- Distances are stored in kilometres (numeric), computed with haversine.
-- All ids are uuid v4 generated by the database (gen_random_uuid, PG13+).
-- =====================================================================

-- ------------------------------ enums --------------------------------
DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('customer', 'admin');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE fulfilment_type AS ENUM ('delivery', 'pickup');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE order_status AS ENUM (
    'awaiting_payment',   -- online payment started but not captured
    'confirmed',          -- paid (or pay-later accepted) and accepted by the store
    'preparing',          -- staff is packing the order
    'ready_for_pickup',   -- pickup orders: bag is on the counter
    'out_for_delivery',   -- delivery orders: with the delivery rider
    'delivered',          -- handed over to the customer (both types)
    'cancelled'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 'submitted' is the UPI-QR middle state: the customer says they have paid and
-- has given a reference, but the shop has not yet seen the money land. It is
-- deliberately not 'paid' — only a human confirming the bank alert does that.
DO $$ BEGIN
  CREATE TYPE payment_status AS ENUM ('pending', 'submitted', 'paid', 'failed', 'refunded');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE payment_method AS ENUM ('upi_qr', 'razorpay', 'pay_on_delivery', 'pay_at_store');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Databases created before UPI QR existed get the new labels added in place.
-- ALTER TYPE … ADD VALUE is idempotent with IF NOT EXISTS, and migrate.js runs
-- these as standalone statements so the new labels are committed before any
-- later statement could reference them.

-- ---------------------------- store config ---------------------------
-- Single-row table: the physical shop. Delivery distance is measured
-- from these coordinates.
CREATE TABLE IF NOT EXISTS store_settings (
  id                     smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  name                   text        NOT NULL,
  tagline                text,
  phone                  text        NOT NULL,
  address_line           text        NOT NULL,
  city                   text        NOT NULL,
  state                  text        NOT NULL,
  pincode                text        NOT NULL,
  latitude               numeric(9,6)  NOT NULL,
  longitude              numeric(9,6)  NOT NULL,
  opens_at               time        NOT NULL DEFAULT '07:00',
  closes_at              time        NOT NULL DEFAULT '21:30',
  free_delivery_radius_km numeric(5,2) NOT NULL DEFAULT 5.00,
  max_delivery_radius_km  numeric(5,2) NOT NULL DEFAULT 5.00,
  min_order_paise        integer     NOT NULL DEFAULT 0, -- delivery only; pickup has no minimum
  base_prep_minutes      integer     NOT NULL DEFAULT 20,
  minutes_per_km         integer     NOT NULL DEFAULT 5,
  accepts_pay_later      boolean     NOT NULL DEFAULT true,
  -- UPI QR: the shop's own VPA. Money moves bank-to-bank; nothing here but
  -- the payee handle, which is public information printed on the counter QR.
  upi_vpa                text,
  upi_payee_name         text,
  accepts_upi_qr         boolean     NOT NULL DEFAULT true,
  updated_at             timestamptz NOT NULL DEFAULT now()
);

-- Idempotent top-ups for databases created before these columns existed.
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS upi_vpa        text;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS upi_payee_name text;
ALTER TABLE store_settings ADD COLUMN IF NOT EXISTS accepts_upi_qr boolean NOT NULL DEFAULT true;

-- Concentric delivery bands. Anything inside free_delivery_radius_km is
-- free; bands let the shop later charge for a wider radius without a
-- code change.
CREATE TABLE IF NOT EXISTS delivery_zones (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name               text         NOT NULL,
  max_distance_km    numeric(5,2) NOT NULL,
  delivery_fee_paise integer      NOT NULL DEFAULT 0 CHECK (delivery_fee_paise >= 0),
  min_order_paise    integer      NOT NULL DEFAULT 0 CHECK (min_order_paise >= 0),
  eta_minutes        integer      NOT NULL DEFAULT 45,
  is_active          boolean      NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS delivery_zones_distance_idx ON delivery_zones (max_distance_km);

-- Pincode centroids used to place an address on the map when the
-- browser geolocation permission is denied.
CREATE TABLE IF NOT EXISTS pincode_centroids (
  pincode    text PRIMARY KEY,
  area       text         NOT NULL,
  city       text         NOT NULL,
  state      text         NOT NULL,
  latitude   numeric(9,6) NOT NULL,
  longitude  numeric(9,6) NOT NULL
);

-- ------------------------------- users -------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name          text        NOT NULL,
  phone         text        NOT NULL UNIQUE,
  email         text        UNIQUE,
  password_hash text        NOT NULL,
  role          user_role   NOT NULL DEFAULT 'customer',
  preferences   jsonb       NOT NULL DEFAULT '{}'::jsonb,
  is_active     boolean     NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS users_role_idx ON users (role);

-- Refresh tokens are stored hashed so a database leak cannot be replayed.
CREATE TABLE IF NOT EXISTS refresh_tokens (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash text        NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS refresh_tokens_user_idx ON refresh_tokens (user_id);

CREATE TABLE IF NOT EXISTS addresses (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  label      text        NOT NULL DEFAULT 'Home',
  contact_name  text     NOT NULL,
  contact_phone text     NOT NULL,
  line1      text        NOT NULL,
  line2      text,
  landmark   text,
  city       text        NOT NULL,
  state      text        NOT NULL,
  pincode    text        NOT NULL,
  latitude   numeric(9,6) NOT NULL,
  longitude  numeric(9,6) NOT NULL,
  is_default boolean     NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS addresses_user_idx ON addresses (user_id);
-- At most one default address per user.
CREATE UNIQUE INDEX IF NOT EXISTS addresses_one_default_per_user
  ON addresses (user_id) WHERE is_default;

-- ----------------------------- catalogue -----------------------------
CREATE TABLE IF NOT EXISTS categories (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text    NOT NULL,
  slug        text    NOT NULL UNIQUE,
  description text,
  emoji       text,
  image_url   text,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true
);
CREATE INDEX IF NOT EXISTS categories_sort_idx ON categories (sort_order);

CREATE TABLE IF NOT EXISTS products (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id   uuid    NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
  name          text    NOT NULL,
  slug          text    NOT NULL UNIQUE,
  brand         text,
  description   text,
  unit_label    text    NOT NULL,                -- "1 kg", "500 g", "6 pcs"
  price_paise   integer NOT NULL CHECK (price_paise > 0),
  mrp_paise     integer NOT NULL CHECK (mrp_paise > 0),
  image_url     text,
  stock_qty     integer NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
  max_per_order integer NOT NULL DEFAULT 20 CHECK (max_per_order > 0),
  is_active     boolean NOT NULL DEFAULT true,
  is_popular    boolean NOT NULL DEFAULT false,
  sold_count    integer NOT NULL DEFAULT 0,
  tags          text[]  NOT NULL DEFAULT '{}',
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT products_price_within_mrp CHECK (price_paise <= mrp_paise)
);
CREATE INDEX IF NOT EXISTS products_category_idx ON products (category_id);
CREATE INDEX IF NOT EXISTS products_active_idx   ON products (is_active);
CREATE INDEX IF NOT EXISTS products_price_idx    ON products (price_paise);
CREATE INDEX IF NOT EXISTS products_popular_idx  ON products (sold_count DESC);
-- Trigram index powers the "as you type" search over name + brand.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS products_search_trgm_idx
  ON products USING gin ((name || ' ' || coalesce(brand, '')) gin_trgm_ops);

-- ------------------------------- cart --------------------------------
CREATE TABLE IF NOT EXISTS carts (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid        NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cart_items (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cart_id    uuid    NOT NULL REFERENCES carts (id) ON DELETE CASCADE,
  product_id uuid    NOT NULL REFERENCES products (id) ON DELETE CASCADE,
  quantity   integer NOT NULL CHECK (quantity > 0),
  added_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (cart_id, product_id)
);
CREATE INDEX IF NOT EXISTS cart_items_cart_idx ON cart_items (cart_id);

-- ------------------------------ orders -------------------------------
CREATE TABLE IF NOT EXISTS orders (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number       text        NOT NULL UNIQUE,
  user_id            uuid        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
  status             order_status    NOT NULL DEFAULT 'awaiting_payment',
  fulfilment         fulfilment_type NOT NULL,
  payment_method     payment_method  NOT NULL,
  payment_status     payment_status  NOT NULL DEFAULT 'pending',

  -- Delivery address is snapshotted: editing the saved address later
  -- must not rewrite the history of a delivered order.
  address_id         uuid REFERENCES addresses (id) ON DELETE SET NULL,
  contact_name       text        NOT NULL,
  contact_phone      text        NOT NULL,
  address_line       text,
  landmark           text,
  city               text,
  pincode            text,
  latitude           numeric(9,6),
  longitude          numeric(9,6),
  distance_km        numeric(6,2),

  slot_start         timestamptz,       -- scheduled pickup / delivery window
  slot_end           timestamptz,
  eta_minutes        integer,
  customer_note      text,

  subtotal_paise     integer NOT NULL CHECK (subtotal_paise >= 0),
  savings_paise      integer NOT NULL DEFAULT 0 CHECK (savings_paise >= 0),
  delivery_fee_paise integer NOT NULL DEFAULT 0 CHECK (delivery_fee_paise >= 0),
  total_paise        integer NOT NULL CHECK (total_paise >= 0),

  placed_at          timestamptz NOT NULL DEFAULT now(),
  completed_at       timestamptz,
  cancelled_at       timestamptz,
  cancel_reason      text,
  updated_at         timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT orders_delivery_needs_location CHECK (
    fulfilment <> 'delivery' OR (latitude IS NOT NULL AND longitude IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS orders_user_idx    ON orders (user_id, placed_at DESC);
CREATE INDEX IF NOT EXISTS orders_status_idx  ON orders (status, placed_at DESC);

CREATE TABLE IF NOT EXISTS order_items (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id         uuid    NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  product_id       uuid    REFERENCES products (id) ON DELETE SET NULL,
  product_name     text    NOT NULL,      -- snapshot
  unit_label       text    NOT NULL,      -- snapshot
  image_url        text,
  unit_price_paise integer NOT NULL CHECK (unit_price_paise >= 0),
  mrp_paise        integer NOT NULL CHECK (mrp_paise >= 0),
  quantity         integer NOT NULL CHECK (quantity > 0),
  line_total_paise integer NOT NULL CHECK (line_total_paise >= 0)
);
CREATE INDEX IF NOT EXISTS order_items_order_idx ON order_items (order_id);

CREATE TABLE IF NOT EXISTS order_status_history (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id   uuid        NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  status     order_status NOT NULL,
  note       text,
  changed_by uuid        REFERENCES users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS order_status_history_order_idx
  ON order_status_history (order_id, created_at);

-- ----------------------------- payments ------------------------------
CREATE TABLE IF NOT EXISTS payments (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id            uuid           NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  provider            text           NOT NULL DEFAULT 'razorpay',
  provider_order_id   text,
  provider_payment_id text UNIQUE,
  amount_paise        integer        NOT NULL CHECK (amount_paise >= 0),
  currency            text           NOT NULL DEFAULT 'INR',
  status              payment_status NOT NULL DEFAULT 'pending',
  method_detail       text,
  error_description   text,
  raw_payload         jsonb          NOT NULL DEFAULT '{}'::jsonb,
  -- UPI QR only. upi_uri is the exact payload encoded in the QR the customer
  -- scanned; upi_reference is the UTR they typed in; verified_by/at is the
  -- staff member who matched it against the bank alert.
  upi_uri             text,
  upi_reference       text,
  expires_at          timestamptz,
  verified_by         uuid           REFERENCES users (id) ON DELETE SET NULL,
  verified_at         timestamptz,
  created_at          timestamptz    NOT NULL DEFAULT now(),
  updated_at          timestamptz    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS payments_order_idx ON payments (order_id);
CREATE INDEX IF NOT EXISTS payments_provider_order_idx ON payments (provider_order_id);

ALTER TABLE payments ADD COLUMN IF NOT EXISTS upi_uri       text;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS upi_reference text;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS expires_at    timestamptz;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS verified_by   uuid REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS verified_at   timestamptz;

-- One customer must not be able to claim another order with the same UTR.
CREATE UNIQUE INDEX IF NOT EXISTS payments_upi_reference_idx
  ON payments (upi_reference) WHERE upi_reference IS NOT NULL;

-- Human readable order numbers: KS-<yy><ddd>-<seq>
CREATE SEQUENCE IF NOT EXISTS order_number_seq START 1001;

-- --------------------------- updated_at ------------------------------
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users','addresses','products','carts','orders','payments','store_settings'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I_touch_updated_at ON %I', t, t);
    EXECUTE format(
      'CREATE TRIGGER %I_touch_updated_at BEFORE UPDATE ON %I
         FOR EACH ROW EXECUTE FUNCTION touch_updated_at()', t, t);
  END LOOP;
END $$;
